### ISSUE TITLE
Chacha and Salsa are two different stream cyphers, from the same family

### ISSUE THREAD

**Issue by toscalix** [scanoss/crypto_algorithms_open_dataset#28]
## Background

As explained by Daniel J. Bernstein in [this paper](https://cr.yp.to/chacha/chacha-20080128.pdf), ChaCha is a variant of Salsa20. Apparently (to be confirmed by an expert)

`"ChaCha follows the same basic design principles as Salsa20,  but I changed some of the details, most importantly to increase the amount of diffusion per round. " `

## Description

Salsa and Chacha should be considered different algorithms

**Comment by scanoss-qg** [comment]
I think we should rename Chacha. The algorithms were splitted in a previous version
